"""Import all models here so Alembic and SQLAlchemy see the full metadata."""

from app.db.base import Base
from app.models.ai import AiGeneration, AiModel, AiProvider
from app.models.ai_readiness import AiReadinessAudit, AiReadinessObservation, ReadinessCategory
from app.models.auth_audit_log import AuthAuditLog, AuthEvent
from app.models.competitor import Competitor
from app.models.crawl import (
    CrawlJob,
    CrawlStatus,
    CrawlType,
    CrawlUrl,
    CrawlUrlStatus,
    PageVersion,
    WebsitePage,
)
from app.models.domain import Domain
from app.models.entities import (
    Entity,
    EntityLink,
    EntityObservation,
    EntityScope,
    SchemaIssue,
)
from app.models.gaps import CitationGap, GapConfidence, GapStatus, GapType
from app.models.intelligence import (
    BrandMention,
    CompetitorMention,
    ResponseCitation,
    ResponseClaim,
)
from app.models.membership import Membership, MembershipRole, OrganizationMember
from app.models.organization import Organization, OrganizationPlan, OrganizationStatus
from app.models.page_intelligence import (
    LinkStatus,
    LinkType,
    PageContentMetrics,
    PageHeading,
    PageImage,
    PageLink,
    PageMetadata,
    PageStructuredData,
    StructuredDataFormat,
)
from app.models.project import Project, ProjectStatus
from app.models.prompts import (
    AiResponse,
    AiUsageRecord,
    BatchStatus,
    ExecutionPriority,
    FunnelStage,
    Prompt,
    PromptCategory,
    PromptIntent,
    PromptRun,
    PromptRunBatch,
    PromptRunStatus,
    PromptSet,
    PromptSetStatus,
    PromptSource,
)
from app.models.recommendations import (
    Recommendation,
    RecommendationPriority,
    RecommendationStatus,
    RecommendationType,
)
from app.models.refresh_token import RefreshToken
from app.models.seo import (
    AuditStatus,
    ObservationCategory,
    ObservationStatus,
    SeoAudit,
    SeoObservation,
    Severity,
)
from app.models.sources import (
    CitationEntity,
    CitationEntityType,
    CitationRelationship,
    DomainType,
    ProjectSource,
    SourceDomain,
    SourcePage,
)
from app.models.user import User

__all__ = [
    "AiGeneration",
    "AiModel",
    "AiProvider",
    "AiReadinessAudit",
    "AiReadinessObservation",
    "ReadinessCategory",
    "AuditStatus",
    "AuthAuditLog",
    "AuthEvent",
    "Base",
    "Competitor",
    "CrawlJob",
    "CrawlStatus",
    "CrawlType",
    "CrawlUrl",
    "CrawlUrlStatus",
    "PageVersion",
    "WebsitePage",
    "Domain",
    "BrandMention",
    "CompetitorMention",
    "ResponseCitation",
    "ResponseClaim",
    "Entity",
    "EntityLink",
    "EntityObservation",
    "EntityScope",
    "SchemaIssue",
    "LinkStatus",
    "LinkType",
    "Membership",
    "MembershipRole",
    "ObservationCategory",
    "ObservationStatus",
    "Organization",
    "OrganizationMember",
    "OrganizationPlan",
    "OrganizationStatus",
    "PageContentMetrics",
    "PageHeading",
    "PageImage",
    "PageLink",
    "PageMetadata",
    "PageStructuredData",
    "Project",
    "Prompt",
    "AiResponse",
    "AiUsageRecord",
    "BatchStatus",
    "ExecutionPriority",
    "PromptRunBatch",
    "PromptCategory",
    "PromptIntent",
    "PromptRun",
    "PromptRunStatus",
    "PromptSet",
    "PromptSetStatus",
    "PromptSource",
    "FunnelStage",
    "ProjectStatus",
    "RefreshToken",
    "SeoAudit",
    "SeoObservation",
    "Severity",
    "StructuredDataFormat",
    "User",
    "Recommendation",
    "RecommendationPriority",
    "RecommendationStatus",
    "RecommendationType",
    "CitationGap",
    "GapConfidence",
    "GapStatus",
    "GapType",
    "CitationEntity",
    "CitationEntityType",
    "CitationRelationship",
    "DomainType",
    "ProjectSource",
    "SourceDomain",
    "SourcePage",
]
