from fastapi import APIRouter

from app.api.v1.routes import (
    ai_readiness,
    auth,
    competitive,
    competitors,
    crawl,
    discovery,
    entities,
    execution,
    gaps,
    graph,
    health,
    insights,
    intelligence,
    organizations,
    pages,
    projects,
    prompts,
    recommendations,
    seo,
    sources,
    visibility,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(organizations.router)
api_router.include_router(projects.org_router)
api_router.include_router(projects.router)
api_router.include_router(competitors.project_router)
api_router.include_router(competitors.router)
api_router.include_router(crawl.project_router)
api_router.include_router(crawl.router)
api_router.include_router(pages.project_router)
api_router.include_router(pages.router)
api_router.include_router(seo.project_router)
api_router.include_router(seo.router)
api_router.include_router(entities.project_router)
api_router.include_router(entities.page_router)
api_router.include_router(ai_readiness.project_router)
api_router.include_router(ai_readiness.router)
api_router.include_router(prompts.project_router)
api_router.include_router(prompts.set_router)
api_router.include_router(prompts.prompt_router)
api_router.include_router(execution.providers_router)
api_router.include_router(execution.set_router)
api_router.include_router(execution.batch_router)
api_router.include_router(execution.prompt_router)
api_router.include_router(intelligence.run_router)
api_router.include_router(intelligence.batch_router)
api_router.include_router(visibility.router)
api_router.include_router(competitive.router)
api_router.include_router(insights.project_router)
api_router.include_router(insights.router)
api_router.include_router(sources.router)
api_router.include_router(sources.project_router)
api_router.include_router(gaps.project_router)
api_router.include_router(gaps.gap_router)
api_router.include_router(graph.router)
api_router.include_router(recommendations.project_router)
api_router.include_router(recommendations.rec_router)
api_router.include_router(discovery.project_router)
api_router.include_router(discovery.router)
