"""citation intelligence sources

Revision ID: 60931a9b8b82
Revises: 95861f7bee76
Create Date: 2026-08-22 19:59:51.805049

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '60931a9b8b82'
down_revision: str | None = '95861f7bee76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_domains',
    sa.Column('hostname', sa.String(length=253), nullable=False),
    sa.Column('normalized_hostname', sa.String(length=253), nullable=False),
    sa.Column('display_name', sa.String(length=253), nullable=False),
    sa.Column('domain_type', sa.String(length=20), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_hostname', name='uq_source_domains_normalized_hostname')
    )
    op.create_index('ix_source_domains_hostname', 'source_domains', ['hostname'], unique=False)
    op.create_index('ix_source_domains_last_seen_at', 'source_domains', ['last_seen_at'], unique=False)
    op.create_table('source_pages',
    sa.Column('source_domain_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_domain_id'], ['source_domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_url', name='uq_source_pages_normalized_url')
    )
    op.create_index('ix_source_pages_last_seen_at', 'source_pages', ['last_seen_at'], unique=False)
    op.create_index('ix_source_pages_source_domain_id', 'source_pages', ['source_domain_id'], unique=False)
    op.create_table('project_sources',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_domain_id', sa.Uuid(), nullable=False),
    sa.Column('source_page_id', sa.Uuid(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('brand_citation_count', sa.Integer(), nullable=False),
    sa.Column('competitor_citation_count', sa.Integer(), nullable=False),
    sa.Column('first_cited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_cited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_domain_id'], ['source_domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_page_id'], ['source_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_domain_id', 'source_page_id', name='uq_project_sources_project_domain_page', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_project_sources_citation_count', 'project_sources', ['citation_count'], unique=False)
    op.create_index('ix_project_sources_project_id', 'project_sources', ['project_id'], unique=False)
    op.create_index('ix_project_sources_source_domain_id', 'project_sources', ['source_domain_id'], unique=False)
    op.create_index('ix_project_sources_source_page_id', 'project_sources', ['source_page_id'], unique=False)
    op.create_table('citation_entities',
    sa.Column('citation_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citation_entities_citation_id', 'citation_entities', ['citation_id'], unique=False)
    op.create_index('ix_citation_entities_entity_id', 'citation_entities', ['entity_id'], unique=False)
    op.create_index('ix_citation_entities_project_id', 'citation_entities', ['project_id'], unique=False)
    # Existing citations predate extraction confidence; 0.5 = "unknown" (matches the model default).
    op.add_column(
        'citations',
        sa.Column('extraction_confidence', sa.Float(), nullable=False, server_default='0.5'),
    )
    op.alter_column('citations', 'extraction_confidence', server_default=None)
    op.add_column('citations', sa.Column('source_domain_id', sa.Uuid(), nullable=True))
    op.add_column('citations', sa.Column('source_page_id', sa.Uuid(), nullable=True))
    op.create_index('ix_citations_project_id', 'citations', ['project_id'], unique=False)
    op.create_index('ix_citations_source_domain_id', 'citations', ['source_domain_id'], unique=False)
    op.create_index('ix_citations_source_page_id', 'citations', ['source_page_id'], unique=False)
    op.create_foreign_key('fk_citations_source_page_id', 'citations', 'source_pages', ['source_page_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_citations_source_domain_id', 'citations', 'source_domains', ['source_domain_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_citations_source_domain_id', 'citations', type_='foreignkey')
    op.drop_constraint('fk_citations_source_page_id', 'citations', type_='foreignkey')
    op.drop_index('ix_citations_source_page_id', table_name='citations')
    op.drop_index('ix_citations_source_domain_id', table_name='citations')
    op.drop_index('ix_citations_project_id', table_name='citations')
    op.drop_column('citations', 'source_page_id')
    op.drop_column('citations', 'source_domain_id')
    op.drop_column('citations', 'extraction_confidence')
    op.drop_index('ix_citation_entities_project_id', table_name='citation_entities')
    op.drop_index('ix_citation_entities_entity_id', table_name='citation_entities')
    op.drop_index('ix_citation_entities_citation_id', table_name='citation_entities')
    op.drop_table('citation_entities')
    op.drop_index('ix_project_sources_source_page_id', table_name='project_sources')
    op.drop_index('ix_project_sources_source_domain_id', table_name='project_sources')
    op.drop_index('ix_project_sources_project_id', table_name='project_sources')
    op.drop_index('ix_project_sources_citation_count', table_name='project_sources')
    op.drop_table('project_sources')
    op.drop_index('ix_source_pages_source_domain_id', table_name='source_pages')
    op.drop_index('ix_source_pages_last_seen_at', table_name='source_pages')
    op.drop_table('source_pages')
    op.drop_index('ix_source_domains_last_seen_at', table_name='source_domains')
    op.drop_index('ix_source_domains_hostname', table_name='source_domains')
    op.drop_table('source_domains')
    # ### end Alembic commands ###
