"""competitor candidates

Revision ID: e09c3c62daaf
Revises: 6053d5ad9c4e
Create Date: 2026-08-22 23:44:20.343333

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "e09c3c62daaf"
down_revision: str | None = "6053d5ad9c4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitor_candidates",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confidence_label", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("competitor_id", sa.Uuid(), nullable=True),
        sa.Column("discovery_version", sa.String(length=40), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["competitor_id"], ["competitors.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "normalized_name", name="uq_competitor_candidates_project_name"
        ),
    )
    op.create_index(
        "ix_competitor_candidates_confidence", "competitor_candidates", ["confidence"], unique=False
    )
    op.create_index(
        "ix_competitor_candidates_project_id", "competitor_candidates", ["project_id"], unique=False
    )
    op.create_index(
        "ix_competitor_candidates_status", "competitor_candidates", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_competitor_candidates_status", table_name="competitor_candidates")
    op.drop_index("ix_competitor_candidates_project_id", table_name="competitor_candidates")
    op.drop_index("ix_competitor_candidates_confidence", table_name="competitor_candidates")
    op.drop_table("competitor_candidates")
    # ### end Alembic commands ###
