"""unique hostnames per project

Revision ID: d1b8f1f89635
Revises: 096963cac3aa
Create Date: 2026-08-22 03:53:29.933258

"""

from collections.abc import Sequence

from alembic import op

revision: str = "d1b8f1f89635"
down_revision: str | None = "096963cac3aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_competitors_project_hostname", "competitors", ["project_id", "hostname"]
    )
    op.create_unique_constraint(
        "uq_domains_project_hostname", "domains", ["project_id", "hostname"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_domains_project_hostname", "domains", type_="unique")
    op.drop_constraint("uq_competitors_project_hostname", "competitors", type_="unique")
    # ### end Alembic commands ###
