"""seo audits and observations

Revision ID: 78e006c1fc69
Revises: 1e588d19332a
Create Date: 2026-08-22 05:32:14.291523

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "78e006c1fc69"
down_revision: str | None = "1e588d19332a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seo_audits",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("crawl_job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "completed", "failed", name="seo_audit_status"),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("pages_analyzed", sa.Integer(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("health_score", sa.Float(), nullable=True),
        sa.Column("score_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["crawl_job_id"], ["crawl_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seo_audits_crawl_job_id"), "seo_audits", ["crawl_job_id"], unique=False
    )
    op.create_index("ix_seo_audits_created_at", "seo_audits", ["created_at"], unique=False)
    op.create_index(
        "ix_seo_audits_project_created", "seo_audits", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_seo_audits_project_id"), "seo_audits", ["project_id"], unique=False)
    op.create_table(
        "seo_observations",
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "indexability",
                "metadata",
                "headings",
                "canonicalization",
                "internal_links",
                "http",
                "structured_data",
                "mobile_html",
                name="seo_observation_category",
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("critical", "high", "medium", "low", "info", name="seo_severity"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "ignored", "resolved", name="seo_observation_status"),
            server_default="open",
            nullable=False,
        ),
        sa.Column("status_note", sa.String(length=1000), nullable=True),
        sa.Column("status_changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["audit_id"], ["seo_audits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["status_changed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_seo_observations_audit_category",
        "seo_observations",
        ["audit_id", "category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seo_observations_audit_id"), "seo_observations", ["audit_id"], unique=False
    )
    op.create_index(
        "ix_seo_observations_audit_severity",
        "seo_observations",
        ["audit_id", "severity"],
        unique=False,
    )
    op.create_index(
        "ix_seo_observations_audit_status", "seo_observations", ["audit_id", "status"], unique=False
    )
    op.create_index(op.f("ix_seo_observations_code"), "seo_observations", ["code"], unique=False)
    op.create_index(
        "ix_seo_observations_created_at", "seo_observations", ["created_at"], unique=False
    )
    op.create_index("ix_seo_observations_page", "seo_observations", ["page_id"], unique=False)
    op.create_index(
        op.f("ix_seo_observations_project_id"), "seo_observations", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_seo_observations_project_id"), table_name="seo_observations")
    op.drop_index("ix_seo_observations_page", table_name="seo_observations")
    op.drop_index("ix_seo_observations_created_at", table_name="seo_observations")
    op.drop_index(op.f("ix_seo_observations_code"), table_name="seo_observations")
    op.drop_index("ix_seo_observations_audit_status", table_name="seo_observations")
    op.drop_index("ix_seo_observations_audit_severity", table_name="seo_observations")
    op.drop_index(op.f("ix_seo_observations_audit_id"), table_name="seo_observations")
    op.drop_index("ix_seo_observations_audit_category", table_name="seo_observations")
    op.drop_table("seo_observations")
    op.drop_index(op.f("ix_seo_audits_project_id"), table_name="seo_audits")
    op.drop_index("ix_seo_audits_project_created", table_name="seo_audits")
    op.drop_index("ix_seo_audits_created_at", table_name="seo_audits")
    op.drop_index(op.f("ix_seo_audits_crawl_job_id"), table_name="seo_audits")
    op.drop_table("seo_audits")
    # ### end Alembic commands ###
    for name in (
        "seo_observation_status",
        "seo_severity",
        "seo_observation_category",
        "seo_audit_status",
    ):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
