"""website intelligence crawler tables

Revision ID: 655812f42b6e
Revises: d1b8f1f89635
Create Date: 2026-08-22 04:23:45.418887

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "655812f42b6e"
down_revision: str | None = "d1b8f1f89635"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_jobs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("root_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "partially_completed",
                "failed",
                "cancelled",
                name="crawl_status",
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column(
            "crawl_type",
            sa.Enum("full", "incremental", "single_page", name="crawl_type"),
            server_default="full",
            nullable=False,
        ),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column("max_depth", sa.Integer(), nullable=False),
        sa.Column("pages_discovered", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pages_crawled", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pages_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pages_skipped", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_crawl_jobs_created_at", "crawl_jobs", ["created_at"], unique=False)
    op.create_index(
        "ix_crawl_jobs_project_created", "crawl_jobs", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_crawl_jobs_project_id"), "crawl_jobs", ["project_id"], unique=False)
    op.create_index("ix_crawl_jobs_status", "crawl_jobs", ["status"], unique=False)
    op.create_table(
        "website_pages",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("normalized_url", sa.String(length=2048), nullable=False),
        sa.Column("canonical_url", sa.String(length=2048), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("html_hash", sa.String(length=64), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("is_duplicate_of_id", sa.Uuid(), nullable=True),
        sa.Column("first_crawled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["is_duplicate_of_id"], ["website_pages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "normalized_url", name="uq_website_pages_project_url"),
    )
    op.create_index("ix_website_pages_created_at", "website_pages", ["created_at"], unique=False)
    op.create_index(
        "ix_website_pages_last_crawled_at", "website_pages", ["last_crawled_at"], unique=False
    )
    op.create_index(
        "ix_website_pages_project_content_hash",
        "website_pages",
        ["project_id", "content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_website_pages_project_id"), "website_pages", ["project_id"], unique=False
    )
    op.create_table(
        "crawl_urls",
        sa.Column("crawl_job_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("normalized_url", sa.String(length=2048), nullable=False),
        sa.Column("parent_url", sa.String(length=2048), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="3", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "discovered",
                "queued",
                "crawling",
                "crawled",
                "failed",
                "skipped",
                name="crawl_url_status",
            ),
            server_default="discovered",
            nullable=False,
        ),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column("page_id", sa.Uuid(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["crawl_job_id"], ["crawl_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crawl_job_id", "normalized_url", name="uq_crawl_urls_job_normalized"),
    )
    op.create_index(
        op.f("ix_crawl_urls_crawl_job_id"), "crawl_urls", ["crawl_job_id"], unique=False
    )
    op.create_index("ix_crawl_urls_discovered_at", "crawl_urls", ["discovered_at"], unique=False)
    op.create_index(
        "ix_crawl_urls_job_status", "crawl_urls", ["crawl_job_id", "status"], unique=False
    )
    op.create_index(op.f("ix_crawl_urls_project_id"), "crawl_urls", ["project_id"], unique=False)
    op.create_index(
        "ix_crawl_urls_project_normalized",
        "crawl_urls",
        ["project_id", "normalized_url"],
        unique=False,
    )
    op.create_table(
        "page_versions",
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("crawl_job_id", sa.Uuid(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("html_hash", sa.String(length=64), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("html_storage_reference", sa.String(length=512), nullable=True),
        sa.Column("crawled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["crawl_job_id"], ["crawl_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_page_versions_crawl_job", "page_versions", ["crawl_job_id"], unique=False)
    op.create_index(
        "ix_page_versions_page_crawled", "page_versions", ["page_id", "crawled_at"], unique=False
    )
    op.create_index(
        op.f("ix_page_versions_project_id"), "page_versions", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_page_versions_project_id"), table_name="page_versions")
    op.drop_index("ix_page_versions_page_crawled", table_name="page_versions")
    op.drop_index("ix_page_versions_crawl_job", table_name="page_versions")
    op.drop_table("page_versions")
    op.drop_index("ix_crawl_urls_project_normalized", table_name="crawl_urls")
    op.drop_index(op.f("ix_crawl_urls_project_id"), table_name="crawl_urls")
    op.drop_index("ix_crawl_urls_job_status", table_name="crawl_urls")
    op.drop_index("ix_crawl_urls_discovered_at", table_name="crawl_urls")
    op.drop_index(op.f("ix_crawl_urls_crawl_job_id"), table_name="crawl_urls")
    op.drop_table("crawl_urls")
    op.drop_index(op.f("ix_website_pages_project_id"), table_name="website_pages")
    op.drop_index("ix_website_pages_project_content_hash", table_name="website_pages")
    op.drop_index("ix_website_pages_last_crawled_at", table_name="website_pages")
    op.drop_index("ix_website_pages_created_at", table_name="website_pages")
    op.drop_table("website_pages")
    op.drop_index("ix_crawl_jobs_status", table_name="crawl_jobs")
    op.drop_index(op.f("ix_crawl_jobs_project_id"), table_name="crawl_jobs")
    op.drop_index("ix_crawl_jobs_project_created", table_name="crawl_jobs")
    op.drop_index("ix_crawl_jobs_created_at", table_name="crawl_jobs")
    op.drop_table("crawl_jobs")
    # ### end Alembic commands ###
    for name in ("crawl_url_status", "crawl_type", "crawl_status"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
