"""source classification

Revision ID: d6bc79c56b20
Revises: 60931a9b8b82
Create Date: 2026-08-22 20:11:36.332308

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d6bc79c56b20"
down_revision: str | None = "60931a9b8b82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_domains", sa.Column("classification_confidence", sa.Float(), nullable=True)
    )
    op.add_column(
        "source_domains",
        sa.Column("classification", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "source_domains",
        sa.Column("is_authority", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("source_domains", "is_authority", server_default=None)
    op.add_column(
        "source_domains", sa.Column("classified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "source_pages",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.alter_column("source_pages", "metadata", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_pages", "metadata")
    op.drop_column("source_domains", "classified_at")
    op.drop_column("source_domains", "is_authority")
    op.drop_column("source_domains", "classification")
    op.drop_column("source_domains", "classification_confidence")
    # ### end Alembic commands ###
