"""content gaps

Revision ID: b56154c699f4
Revises: 0ccf1bd24499
Create Date: 2026-08-23 06:53:31.472427

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "b56154c699f4"
down_revision: str | None = "0ccf1bd24499"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_gaps",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_id", sa.Uuid(), nullable=True),
        sa.Column("topic", sa.String(length=300), nullable=False),
        sa.Column("normalized_topic", sa.String(length=300), nullable=False),
        sa.Column("gap_type", sa.String(length=30), nullable=False),
        sa.Column("competitor_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("customer_coverage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("opportunity_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="fk_content_gaps_project_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"], ["prompts.id"], name="fk_content_gaps_prompt_id", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "normalized_topic", "gap_type", name="uq_content_gaps_project_topic_type"
        ),
    )
    op.create_index(
        "ix_content_gaps_opportunity_score", "content_gaps", ["opportunity_score"], unique=False
    )
    op.create_index("ix_content_gaps_project_id", "content_gaps", ["project_id"], unique=False)
    op.create_index("ix_content_gaps_status", "content_gaps", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_content_gaps_status", table_name="content_gaps")
    op.drop_index("ix_content_gaps_project_id", table_name="content_gaps")
    op.drop_index("ix_content_gaps_opportunity_score", table_name="content_gaps")
    op.drop_table("content_gaps")
    # ### end Alembic commands ###
