"""content briefs

Revision ID: 5401563bd6e4
Revises: 7cc4acbb60e1
Create Date: 2026-08-23 08:05:17.846401

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5401563bd6e4"
down_revision: str | None = "7cc4acbb60e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_briefs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=40), nullable=False),
        sa.Column("target_prompt_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("competitor_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("search_intent", sa.Text(), nullable=False),
        sa.Column("audience", sa.Text(), nullable=False),
        sa.Column("differentiation", sa.Text(), nullable=False),
        sa.Column("outline", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "information_requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("evidence_requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "citation_opportunities", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("entity_requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "internal_link_recommendations", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("confidence", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name="fk_content_briefs_agent_run_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="fk_content_briefs_project_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "source_key", name="uq_content_briefs_project_source_key"
        ),
    )
    op.create_index(
        "ix_content_briefs_content_type", "content_briefs", ["content_type"], unique=False
    )
    op.create_index("ix_content_briefs_project_id", "content_briefs", ["project_id"], unique=False)
    op.create_index("ix_content_briefs_status", "content_briefs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_content_briefs_status", table_name="content_briefs")
    op.drop_index("ix_content_briefs_project_id", table_name="content_briefs")
    op.drop_index("ix_content_briefs_content_type", table_name="content_briefs")
    op.drop_table("content_briefs")
    # ### end Alembic commands ###
