"""entity optimization reviews

Revision ID: d1d1307fed64
Revises: 1ba15eba6ca2
Create Date: 2026-08-23 09:11:32.418203

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d1d1307fed64"
down_revision: str | None = "1ba15eba6ca2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_optimization_reviews",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("review_key", sa.String(length=200), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommendations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name="fk_entity_reviews_agent_run_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["entities.id"], name="fk_entity_reviews_entity_id", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="fk_entity_reviews_project_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "review_key", name="uq_entity_reviews_project_key"),
    )
    op.create_index(
        "ix_entity_reviews_entity_type",
        "entity_optimization_reviews",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        "ix_entity_reviews_project_id", "entity_optimization_reviews", ["project_id"], unique=False
    )
    op.create_index(
        "ix_entity_reviews_status", "entity_optimization_reviews", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_entity_reviews_status", table_name="entity_optimization_reviews")
    op.drop_index("ix_entity_reviews_project_id", table_name="entity_optimization_reviews")
    op.drop_index("ix_entity_reviews_entity_type", table_name="entity_optimization_reviews")
    op.drop_table("entity_optimization_reviews")
    # ### end Alembic commands ###
