"""page intelligence tables and response time

Revision ID: 4eafda8bad0c
Revises: 655812f42b6e
Create Date: 2026-08-22 05:07:09.996817

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "4eafda8bad0c"
down_revision: str | None = "655812f42b6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_content_metrics",
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("paragraph_count", sa.Integer(), nullable=False),
        sa.Column("sentence_count", sa.Integer(), nullable=False),
        sa.Column("reading_time_seconds", sa.Integer(), nullable=False),
        sa.Column("text_to_html_ratio", sa.Float(), nullable=False),
        sa.Column("html_bytes", sa.Integer(), nullable=False),
        sa.Column("heading_count", sa.Integer(), nullable=False),
        sa.Column("h1_count", sa.Integer(), nullable=False),
        sa.Column("link_count", sa.Integer(), nullable=False),
        sa.Column("internal_link_count", sa.Integer(), nullable=False),
        sa.Column("external_link_count", sa.Integer(), nullable=False),
        sa.Column("image_count", sa.Integer(), nullable=False),
        sa.Column("images_missing_alt", sa.Integer(), nullable=False),
        sa.Column("heading_observations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("clean_text", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_version_id"], ["page_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_page_content_metrics_page_id"), "page_content_metrics", ["page_id"], unique=False
    )
    op.create_index(
        op.f("ix_page_content_metrics_project_id"),
        "page_content_metrics",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_page_content_metrics_project_words",
        "page_content_metrics",
        ["project_id", "word_count"],
        unique=False,
    )
    op.create_index(
        "uq_page_content_metrics_page", "page_content_metrics", ["page_id"], unique=True
    )
    op.create_table(
        "page_headings",
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("parent_position", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(length=1000), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_version_id"], ["page_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_headings_page_id"), "page_headings", ["page_id"], unique=False)
    op.create_index(
        "ix_page_headings_page_position", "page_headings", ["page_id", "position"], unique=False
    )
    op.create_index(
        op.f("ix_page_headings_project_id"), "page_headings", ["project_id"], unique=False
    )
    op.create_table(
        "page_images",
        sa.Column("src", sa.String(length=2048), nullable=False),
        sa.Column("alt", sa.String(length=1000), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("loading", sa.String(length=20), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_version_id"], ["page_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_images_page_id"), "page_images", ["page_id"], unique=False)
    op.create_index(
        "ix_page_images_page_position", "page_images", ["page_id", "position"], unique=False
    )
    op.create_index(op.f("ix_page_images_project_id"), "page_images", ["project_id"], unique=False)
    op.create_table(
        "page_links",
        sa.Column("href", sa.String(length=2048), nullable=False),
        sa.Column("normalized_url", sa.String(length=2048), nullable=True),
        sa.Column("anchor_text", sa.String(length=500), nullable=False),
        sa.Column(
            "link_type", sa.Enum("internal", "external", name="page_link_type"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("unknown", "ok", "broken", "invalid", name="page_link_status"),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("target_page_id", sa.Uuid(), nullable=True),
        sa.Column("target_http_status", sa.Integer(), nullable=True),
        sa.Column("is_nofollow", sa.Boolean(), nullable=False),
        sa.Column("is_sponsored", sa.Boolean(), nullable=False),
        sa.Column("is_ugc", sa.Boolean(), nullable=False),
        sa.Column("in_navigation", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_version_id"], ["page_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_page_id"], ["website_pages.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_links_page_id"), "page_links", ["page_id"], unique=False)
    op.create_index(
        "ix_page_links_page_position", "page_links", ["page_id", "position"], unique=False
    )
    op.create_index(op.f("ix_page_links_project_id"), "page_links", ["project_id"], unique=False)
    op.create_index(
        "ix_page_links_project_target", "page_links", ["project_id", "normalized_url"], unique=False
    )
    op.create_index(
        "ix_page_links_project_type", "page_links", ["project_id", "link_type"], unique=False
    )
    op.create_table(
        "page_metadata",
        sa.Column("pathname", sa.String(length=2048), nullable=False),
        sa.Column("robots", sa.String(length=500), nullable=True),
        sa.Column("viewport", sa.String(length=200), nullable=True),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("charset", sa.String(length=40), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("html_lang", sa.String(length=35), nullable=True),
        sa.Column("language", sa.String(length=35), nullable=True),
        sa.Column("language_source", sa.String(length=20), nullable=True),
        sa.Column("language_confidence", sa.Float(), nullable=True),
        sa.Column("open_graph", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("twitter", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("other", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_version_id"], ["page_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_metadata_page_id"), "page_metadata", ["page_id"], unique=False)
    op.create_index(
        op.f("ix_page_metadata_project_id"), "page_metadata", ["project_id"], unique=False
    )
    op.create_index("uq_page_metadata_page", "page_metadata", ["page_id"], unique=True)
    op.add_column("crawl_urls", sa.Column("response_time_ms", sa.Integer(), nullable=True))
    op.add_column("page_versions", sa.Column("response_time_ms", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("page_versions", "response_time_ms")
    op.drop_column("crawl_urls", "response_time_ms")
    op.drop_index("uq_page_metadata_page", table_name="page_metadata")
    op.drop_index(op.f("ix_page_metadata_project_id"), table_name="page_metadata")
    op.drop_index(op.f("ix_page_metadata_page_id"), table_name="page_metadata")
    op.drop_table("page_metadata")
    op.drop_index("ix_page_links_project_type", table_name="page_links")
    op.drop_index("ix_page_links_project_target", table_name="page_links")
    op.drop_index(op.f("ix_page_links_project_id"), table_name="page_links")
    op.drop_index("ix_page_links_page_position", table_name="page_links")
    op.drop_index(op.f("ix_page_links_page_id"), table_name="page_links")
    op.drop_table("page_links")
    op.drop_index(op.f("ix_page_images_project_id"), table_name="page_images")
    op.drop_index("ix_page_images_page_position", table_name="page_images")
    op.drop_index(op.f("ix_page_images_page_id"), table_name="page_images")
    op.drop_table("page_images")
    op.drop_index(op.f("ix_page_headings_project_id"), table_name="page_headings")
    op.drop_index("ix_page_headings_page_position", table_name="page_headings")
    op.drop_index(op.f("ix_page_headings_page_id"), table_name="page_headings")
    op.drop_table("page_headings")
    op.drop_index("uq_page_content_metrics_page", table_name="page_content_metrics")
    op.drop_index("ix_page_content_metrics_project_words", table_name="page_content_metrics")
    op.drop_index(op.f("ix_page_content_metrics_project_id"), table_name="page_content_metrics")
    op.drop_index(op.f("ix_page_content_metrics_page_id"), table_name="page_content_metrics")
    op.drop_table("page_content_metrics")
    # ### end Alembic commands ###
    for name in ("page_link_status", "page_link_type"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
