"""content optimization reviews

Revision ID: 1ba15eba6ca2
Revises: 5401563bd6e4
Create Date: 2026-08-23 08:57:33.761137

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1ba15eba6ca2"
down_revision: str | None = "5401563bd6e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_optimization_reviews",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommendations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposed_changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name="fk_content_reviews_agent_run_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["website_pages.id"], name="fk_content_reviews_page_id", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_content_reviews_project_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "page_id", name="uq_content_reviews_project_page"),
    )
    op.create_index(
        "ix_content_reviews_project_id",
        "content_optimization_reviews",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_content_reviews_score", "content_optimization_reviews", ["score"], unique=False
    )
    op.create_index(
        "ix_content_reviews_status", "content_optimization_reviews", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_content_reviews_status", table_name="content_optimization_reviews")
    op.drop_index("ix_content_reviews_score", table_name="content_optimization_reviews")
    op.drop_index("ix_content_reviews_project_id", table_name="content_optimization_reviews")
    op.drop_table("content_optimization_reviews")
    # ### end Alembic commands ###
