"""citation gaps

Revision ID: dd32486fc9cb
Revises: d6bc79c56b20
Create Date: 2026-08-22 20:20:22.851238

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "dd32486fc9cb"
down_revision: str | None = "d6bc79c56b20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "citation_gaps",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_domain_id", sa.Uuid(), nullable=False),
        sa.Column("source_page_id", sa.Uuid(), nullable=True),
        sa.Column("gap_type", sa.String(length=30), nullable=False),
        sa.Column("brand_citations", sa.Integer(), nullable=False),
        sa.Column("competitor_citations", sa.Integer(), nullable=False),
        sa.Column("relevant_response_count", sa.Integer(), nullable=False),
        sa.Column("opportunity_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("competitors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_domain_id"], ["source_domains.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_page_id"], ["source_pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "source_domain_id",
            "source_page_id",
            name="uq_citation_gaps_project_domain_page",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_citation_gaps_opportunity_score", "citation_gaps", ["opportunity_score"], unique=False
    )
    op.create_index("ix_citation_gaps_project_id", "citation_gaps", ["project_id"], unique=False)
    op.create_index(
        "ix_citation_gaps_source_domain_id", "citation_gaps", ["source_domain_id"], unique=False
    )
    op.create_index("ix_citation_gaps_status", "citation_gaps", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_citation_gaps_status", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_source_domain_id", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_project_id", table_name="citation_gaps")
    op.drop_index("ix_citation_gaps_opportunity_score", table_name="citation_gaps")
    op.drop_table("citation_gaps")
    # ### end Alembic commands ###
