"""auth audit logs

Revision ID: 096963cac3aa
Revises: b2c4d6e8f0a1
Create Date: 2026-08-22 03:45:21.493541

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "096963cac3aa"
down_revision: str | None = "b2c4d6e8f0a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_audit_logs",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event",
            sa.Enum(
                "signup",
                "login_succeeded",
                "login_failed",
                "token_refreshed",
                "refresh_reuse_detected",
                "logout",
                "logout_all",
                name="auth_event",
            ),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_auth_audit_logs_created_at", "auth_audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_auth_audit_logs_user_event", "auth_audit_logs", ["user_id", "event"], unique=False
    )
    op.create_index(
        op.f("ix_auth_audit_logs_user_id"), "auth_audit_logs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_audit_logs_user_id"), table_name="auth_audit_logs")
    op.drop_index("ix_auth_audit_logs_user_event", table_name="auth_audit_logs")
    op.drop_index("ix_auth_audit_logs_created_at", table_name="auth_audit_logs")
    op.drop_table("auth_audit_logs")
    sa.Enum(name="auth_event").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
