"""prompt execution batches responses usage

Revision ID: 52e1cfac7d44
Revises: 6bce85b8f83b
Create Date: 2026-08-22 18:37:26.074194

"""
from collections.abc import Sequence

import json

import sqlalchemy as sa
from alembic import op

from app.ai.catalog import DEFAULT_PRICING, default_pricing
from sqlalchemy.dialects import postgresql

revision: str = '52e1cfac7d44'
down_revision: str | None = '6bce85b8f83b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE prompt_run_status ADD VALUE IF NOT EXISTS 'cancelled'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_run_batches',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_set_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'cancelling', 'cancelled', name='prompt_run_batch_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', name='execution_priority'), nullable=False),
    sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('completed_runs', sa.Integer(), nullable=False),
    sa.Column('failed_runs', sa.Integer(), nullable=False),
    sa.Column('cancelled_runs', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_set_id'], ['prompt_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_run_batches_created_at', 'prompt_run_batches', ['created_at'], unique=False)
    op.create_index('ix_prompt_run_batches_project_created', 'prompt_run_batches', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_prompt_run_batches_project_id'), 'prompt_run_batches', ['project_id'], unique=False)
    op.create_index(op.f('ix_prompt_run_batches_prompt_set_id'), 'prompt_run_batches', ['prompt_set_id'], unique=False)
    op.create_table('ai_responses',
    sa.Column('prompt_run_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('finish_reason', sa.String(length=30), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('provider_request_id', sa.String(length=200), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_run_id')
    )
    op.create_index('ix_ai_responses_created_at', 'ai_responses', ['created_at'], unique=False)
    op.create_table('ai_usage_records',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_run_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pricing_version', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_usage_records_created_at', 'ai_usage_records', ['created_at'], unique=False)
    op.create_index('ix_ai_usage_records_org_created', 'ai_usage_records', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_ai_usage_records_project_created', 'ai_usage_records', ['project_id', 'created_at'], unique=False)
    op.add_column('ai_models', sa.Column('pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.alter_column('ai_models', 'pricing', server_default=None)
    bind = op.get_bind()
    for model_key in DEFAULT_PRICING:
        bind.execute(
            sa.text("UPDATE ai_models SET pricing = CAST(:pricing AS jsonb) WHERE model_key = :model_key"),
            {"pricing": json.dumps(default_pricing(model_key)), "model_key": model_key},
        )
    op.add_column('prompt_runs', sa.Column('batch_id', sa.Uuid(), nullable=True))
    op.add_column('prompt_runs', sa.Column('provider_id', sa.Uuid(), nullable=True))
    op.add_column('prompt_runs', sa.Column('model_id', sa.Uuid(), nullable=True))
    op.add_column('prompt_runs', sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('prompt_runs', 'attempts', server_default=None)
    op.add_column('prompt_runs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('prompt_runs', sa.Column('error_code', sa.String(length=40), nullable=True))
    op.create_index('ix_prompt_runs_batch_status', 'prompt_runs', ['batch_id', 'status'], unique=False)
    op.create_foreign_key('fk_prompt_runs_batch_id', 'prompt_runs', 'prompt_run_batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_prompt_runs_model_id', 'prompt_runs', 'ai_models', ['model_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_prompt_runs_provider_id', 'prompt_runs', 'ai_providers', ['provider_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_prompt_runs_provider_id', 'prompt_runs', type_='foreignkey')
    op.drop_constraint('fk_prompt_runs_model_id', 'prompt_runs', type_='foreignkey')
    op.drop_constraint('fk_prompt_runs_batch_id', 'prompt_runs', type_='foreignkey')
    op.drop_index('ix_prompt_runs_batch_status', table_name='prompt_runs')
    op.drop_column('prompt_runs', 'error_code')
    op.drop_column('prompt_runs', 'latency_ms')
    op.drop_column('prompt_runs', 'attempts')
    op.drop_column('prompt_runs', 'model_id')
    op.drop_column('prompt_runs', 'provider_id')
    op.drop_column('prompt_runs', 'batch_id')
    op.drop_column('ai_models', 'pricing')
    op.drop_index('ix_ai_usage_records_project_created', table_name='ai_usage_records')
    op.drop_index('ix_ai_usage_records_org_created', table_name='ai_usage_records')
    op.drop_index('ix_ai_usage_records_created_at', table_name='ai_usage_records')
    op.drop_table('ai_usage_records')
    op.drop_index('ix_ai_responses_created_at', table_name='ai_responses')
    op.drop_table('ai_responses')
    op.drop_index(op.f('ix_prompt_run_batches_prompt_set_id'), table_name='prompt_run_batches')
    op.drop_index(op.f('ix_prompt_run_batches_project_id'), table_name='prompt_run_batches')
    op.drop_index('ix_prompt_run_batches_project_created', table_name='prompt_run_batches')
    op.drop_index('ix_prompt_run_batches_created_at', table_name='prompt_run_batches')
    op.drop_table('prompt_run_batches')
    for name in ('prompt_run_batch_status', 'execution_priority'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # Postgres cannot remove an enum value; 'cancelled' stays on prompt_run_status.
    # ### end Alembic commands ###
