"""ai readiness audits

Revision ID: 6f34b05b9073
Revises: 3dd3630d9851
Create Date: 2026-08-22 16:58:14.146943

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6f34b05b9073'
down_revision: str | None = '3dd3630d9851'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_readiness_audits',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'running', 'completed', 'failed', name='seo_audit_status', create_type=False), server_default='queued', nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('pages_analyzed', sa.Integer(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_readiness_audits_created_at', 'ai_readiness_audits', ['created_at'], unique=False)
    op.create_index('ix_ai_readiness_audits_project_created', 'ai_readiness_audits', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_readiness_audits_project_id'), 'ai_readiness_audits', ['project_id'], unique=False)
    op.create_table('ai_readiness_observations',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.Enum('entity_clarity', 'product_clarity', 'evidence', 'authority', 'content_structure', 'faq', 'comparison', 'factual_consistency', name='ai_readiness_category'), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('severity', postgresql.ENUM('critical', 'high', 'medium', 'low', 'info', name='seo_severity', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['ai_readiness_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['website_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_readiness_observations_audit_category', 'ai_readiness_observations', ['audit_id', 'category'], unique=False)
    op.create_index(op.f('ix_ai_readiness_observations_audit_id'), 'ai_readiness_observations', ['audit_id'], unique=False)
    op.create_index('ix_ai_readiness_observations_audit_severity', 'ai_readiness_observations', ['audit_id', 'severity'], unique=False)
    op.create_index(op.f('ix_ai_readiness_observations_code'), 'ai_readiness_observations', ['code'], unique=False)
    op.create_index('ix_ai_readiness_observations_created_at', 'ai_readiness_observations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_readiness_observations_project_id'), 'ai_readiness_observations', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_readiness_observations_project_id'), table_name='ai_readiness_observations')
    op.drop_index('ix_ai_readiness_observations_created_at', table_name='ai_readiness_observations')
    op.drop_index(op.f('ix_ai_readiness_observations_code'), table_name='ai_readiness_observations')
    op.drop_index('ix_ai_readiness_observations_audit_severity', table_name='ai_readiness_observations')
    op.drop_index(op.f('ix_ai_readiness_observations_audit_id'), table_name='ai_readiness_observations')
    op.drop_index('ix_ai_readiness_observations_audit_category', table_name='ai_readiness_observations')
    op.drop_table('ai_readiness_observations')
    op.drop_index(op.f('ix_ai_readiness_audits_project_id'), table_name='ai_readiness_audits')
    op.drop_index('ix_ai_readiness_audits_project_created', table_name='ai_readiness_audits')
    op.drop_index('ix_ai_readiness_audits_created_at', table_name='ai_readiness_audits')
    op.drop_table('ai_readiness_audits')
    sa.Enum(name='ai_readiness_category').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
