"""notification channels

Revision ID: c09256688932
Revises: 6c69eb8fd272
Create Date: 2026-09-24 06:01:10.880657

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c09256688932"
down_revision: str | None = "6c69eb8fd272"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_channels",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel_type",
            sa.Enum("webhook", name="notification_channel_type"),
            server_default="webhook",
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("secret", sa.String(length=512), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("last_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_delivery_status",
            sa.Enum("delivered", "failed", name="notification_delivery_status"),
            nullable=True,
        ),
        sa.Column("last_delivery_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            ondelete="SET NULL",
            name="fk_notification_channels_created_by_user_id",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            ondelete="CASCADE",
            name="fk_notification_channels_project_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_channels_project_enabled",
        "notification_channels",
        ["project_id", "enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_channels_project_id"),
        "notification_channels",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_channels_project_id"), table_name="notification_channels")
    op.drop_index("ix_notification_channels_project_enabled", table_name="notification_channels")
    op.drop_table("notification_channels")
    sa.Enum(name="notification_channel_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="notification_delivery_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
