"""prompt sets prompts and runs

Revision ID: 6bce85b8f83b
Revises: f0e4f4a9ac3f
Create Date: 2026-08-22 18:12:35.945593

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "6bce85b8f83b"
down_revision: str | None = "f0e4f4a9ac3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_sets",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "discovery",
                "comparison",
                "recommendation",
                "pricing",
                "product",
                "alternative",
                "problem_solution",
                "industry",
                "local",
                "transactional",
                name="prompt_category",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "archived", name="prompt_set_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("generation_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_prompt_sets_created_at", "prompt_sets", ["created_at"], unique=False)
    op.create_index(
        "ix_prompt_sets_project_created", "prompt_sets", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_prompt_sets_project_id"), "prompt_sets", ["project_id"], unique=False)
    op.create_table(
        "prompts",
        sa.Column("prompt_set_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("normalized_text", sa.String(length=500), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM(
                "discovery",
                "comparison",
                "recommendation",
                "pricing",
                "product",
                "alternative",
                "problem_solution",
                "industry",
                "local",
                "transactional",
                name="prompt_category",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "intent",
            sa.Enum(
                "informational", "commercial", "transactional", "navigational", name="prompt_intent"
            ),
            nullable=False,
        ),
        sa.Column(
            "funnel_stage",
            sa.Enum(
                "awareness",
                "consideration",
                "decision",
                "purchase",
                "retention",
                name="prompt_funnel_stage",
            ),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("source", sa.Enum("generated", "manual", name="prompt_source"), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("quality_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prompt_set_id"], ["prompt_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_prompts_created_at", "prompts", ["created_at"], unique=False)
    op.create_index(
        "ix_prompts_project_category", "prompts", ["project_id", "category"], unique=False
    )
    op.create_index(op.f("ix_prompts_project_id"), "prompts", ["project_id"], unique=False)
    op.create_index(op.f("ix_prompts_prompt_set_id"), "prompts", ["prompt_set_id"], unique=False)
    op.create_index(
        "ix_prompts_set_normalized", "prompts", ["prompt_set_id", "normalized_text"], unique=True
    )
    op.create_table(
        "prompt_runs",
        sa.Column("prompt_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "completed", "failed", name="prompt_run_status"),
            nullable=False,
        ),
        sa.Column("provider_key", sa.String(length=40), nullable=True),
        sa.Column("model_key", sa.String(length=120), nullable=True),
        sa.Column("ai_generation_id", sa.Uuid(), nullable=True),
        sa.Column("visibility", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ai_generation_id"], ["ai_generations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_prompt_runs_created_at", "prompt_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_prompt_runs_project_id"), "prompt_runs", ["project_id"], unique=False)
    op.create_index(
        "ix_prompt_runs_prompt_created", "prompt_runs", ["prompt_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_prompt_runs_prompt_id"), "prompt_runs", ["prompt_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompt_runs_prompt_id"), table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_prompt_created", table_name="prompt_runs")
    op.drop_index(op.f("ix_prompt_runs_project_id"), table_name="prompt_runs")
    op.drop_index("ix_prompt_runs_created_at", table_name="prompt_runs")
    op.drop_table("prompt_runs")
    op.drop_index("ix_prompts_set_normalized", table_name="prompts")
    op.drop_index(op.f("ix_prompts_prompt_set_id"), table_name="prompts")
    op.drop_index(op.f("ix_prompts_project_id"), table_name="prompts")
    op.drop_index("ix_prompts_project_category", table_name="prompts")
    op.drop_index("ix_prompts_created_at", table_name="prompts")
    op.drop_table("prompts")
    op.drop_index(op.f("ix_prompt_sets_project_id"), table_name="prompt_sets")
    op.drop_index("ix_prompt_sets_project_created", table_name="prompt_sets")
    op.drop_index("ix_prompt_sets_created_at", table_name="prompt_sets")
    op.drop_table("prompt_sets")
    for name in (
        "prompt_run_status",
        "prompt_source",
        "prompt_funnel_stage",
        "prompt_intent",
        "prompt_set_status",
        "prompt_category",
    ):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
