"""competitor intelligence

Revision ID: 6053d5ad9c4e
Revises: 1f489b701689
Create Date: 2026-08-22 23:30:51.971189

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6053d5ad9c4e"
down_revision: str | None = "1f489b701689"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitor_aliases",
        sa.Column("competitor_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.Column("normalized_alias", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["competitor_id"], ["competitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "competitor_id", "alias", name="uq_competitor_aliases_competitor_alias"
        ),
    )
    op.create_index(
        "ix_competitor_aliases_competitor_id", "competitor_aliases", ["competitor_id"], unique=False
    )
    op.create_index(
        "ix_competitor_aliases_normalized_alias",
        "competitor_aliases",
        ["normalized_alias"],
        unique=False,
    )
    op.create_table(
        "competitor_domains",
        sa.Column("competitor_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("domain_type", sa.String(length=20), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["competitor_id"], ["competitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "competitor_id", "domain", name="uq_competitor_domains_competitor_domain"
        ),
    )
    op.create_index(
        "ix_competitor_domains_competitor_id", "competitor_domains", ["competitor_id"], unique=False
    )
    op.create_index("ix_competitor_domains_domain", "competitor_domains", ["domain"], unique=False)
    op.create_table(
        "competitor_products",
        sa.Column("competitor_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["competitor_id"], ["competitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "competitor_id", "normalized_name", name="uq_competitor_products_competitor_name"
        ),
    )
    op.create_index(
        "ix_competitor_products_competitor_id",
        "competitor_products",
        ["competitor_id"],
        unique=False,
    )
    # Extend the existing competitors table. Existing rows are manual, active, high-confidence;
    # normalized_name / normalized_domain are derived from the stored name / hostname and a
    # primary competitor_domains row is created for each existing competitor.
    op.add_column("competitors", sa.Column("normalized_name", sa.String(length=200), nullable=True))
    op.add_column(
        "competitors", sa.Column("normalized_domain", sa.String(length=253), nullable=True)
    )
    op.add_column("competitors", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "competitors",
        sa.Column("source", sa.String(length=20), nullable=False, server_default="manual"),
    )
    op.add_column(
        "competitors",
        sa.Column("status", sa.String(length=20), nullable=False, server_default="active"),
    )
    op.add_column(
        "competitors",
        sa.Column("confidence", sa.String(length=10), nullable=False, server_default="high"),
    )
    op.execute(
        """
        UPDATE competitors SET
          normalized_name = regexp_replace(lower(name), '[^a-z0-9]+', '', 'g'),
          normalized_domain = regexp_replace(lower(hostname), '^www\\.', '')
        """
    )
    # Names that collapse to the same normalized form within a project would violate the new
    # unique constraint; make them distinct by suffixing the short id (operators can rename).
    op.execute(
        """
        UPDATE competitors c SET normalized_name = c.normalized_name || left(c.id::text, 8)
        WHERE EXISTS (
          SELECT 1 FROM competitors o
          WHERE o.project_id = c.project_id AND o.normalized_name = c.normalized_name
            AND o.created_at < c.created_at
        )
        """
    )
    op.execute(
        """
        INSERT INTO competitor_domains (id, competitor_id, domain, domain_type, is_primary, created_at, updated_at)
        SELECT gen_random_uuid(), id, normalized_domain, 'primary', true, now(), now() FROM competitors
        """
    )
    op.alter_column("competitors", "normalized_name", nullable=False)
    op.alter_column("competitors", "normalized_domain", nullable=False)
    op.alter_column("competitors", "source", server_default=None)
    op.alter_column("competitors", "status", server_default=None)
    op.alter_column("competitors", "confidence", server_default=None)
    op.create_index(
        "ix_competitors_normalized_domain", "competitors", ["normalized_domain"], unique=False
    )
    op.create_index("ix_competitors_status", "competitors", ["status"], unique=False)
    op.create_unique_constraint(
        "uq_competitors_project_normalized_name", "competitors", ["project_id", "normalized_name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_competitors_project_normalized_name", "competitors", type_="unique")
    op.drop_index("ix_competitors_status", table_name="competitors")
    op.drop_index("ix_competitors_normalized_domain", table_name="competitors")
    op.drop_column("competitors", "confidence")
    op.drop_column("competitors", "status")
    op.drop_column("competitors", "source")
    op.drop_column("competitors", "description")
    op.drop_column("competitors", "normalized_domain")
    op.drop_column("competitors", "normalized_name")
    op.drop_index("ix_competitor_products_competitor_id", table_name="competitor_products")
    op.drop_table("competitor_products")
    op.drop_index("ix_competitor_domains_domain", table_name="competitor_domains")
    op.drop_index("ix_competitor_domains_competitor_id", table_name="competitor_domains")
    op.drop_table("competitor_domains")
    op.drop_index("ix_competitor_aliases_normalized_alias", table_name="competitor_aliases")
    op.drop_index("ix_competitor_aliases_competitor_id", table_name="competitor_aliases")
    op.drop_table("competitor_aliases")
    # ### end Alembic commands ###
