"""agent workflows

Revision ID: 6c69eb8fd272
Revises: d1d1307fed64
Create Date: 2026-08-23 09:21:14.077472

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "6c69eb8fd272"
down_revision: str | None = "d1d1307fed64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_workflows",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_type", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("hold_reason", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("action_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_agent_workflows_project_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name="fk_agent_workflows_requested_by_user_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_workflows_created_at", "agent_workflows", ["created_at"], unique=False
    )
    op.create_index(
        "ix_agent_workflows_project_id", "agent_workflows", ["project_id"], unique=False
    )
    op.create_index("ix_agent_workflows_status", "agent_workflows", ["status"], unique=False)
    op.create_table(
        "agent_workflow_steps",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("agent_name", sa.String(length=100), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("input_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name="fk_agent_workflow_steps_agent_run_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["agent_workflows.id"],
            name="fk_agent_workflow_steps_workflow_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "sequence", name="uq_workflow_steps_workflow_sequence"),
    )
    op.create_index("ix_workflow_steps_status", "agent_workflow_steps", ["status"], unique=False)
    op.create_index(
        "ix_workflow_steps_workflow_id", "agent_workflow_steps", ["workflow_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workflow_steps_workflow_id", table_name="agent_workflow_steps")
    op.drop_index("ix_workflow_steps_status", table_name="agent_workflow_steps")
    op.drop_table("agent_workflow_steps")
    op.drop_index("ix_agent_workflows_status", table_name="agent_workflows")
    op.drop_index("ix_agent_workflows_project_id", table_name="agent_workflows")
    op.drop_index("ix_agent_workflows_created_at", table_name="agent_workflows")
    op.drop_table("agent_workflows")
    # ### end Alembic commands ###
