"""response intelligence tables

Revision ID: 95861f7bee76
Revises: 52e1cfac7d44
Create Date: 2026-08-22 19:02:10.546512

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '95861f7bee76'
down_revision: str | None = '52e1cfac7d44'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_mentions',
    sa.Column('ai_response_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('mention_text', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('recommendation_strength', sa.String(length=10), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_response_id'], ['ai_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_mentions_ai_response_id'), 'brand_mentions', ['ai_response_id'], unique=False)
    op.create_index('ix_brand_mentions_created_at', 'brand_mentions', ['created_at'], unique=False)
    op.create_index('ix_brand_mentions_project_created', 'brand_mentions', ['project_id', 'created_at'], unique=False)
    op.create_table('citations',
    sa.Column('ai_response_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('domain', sa.String(length=253), nullable=True),
    sa.Column('anchor_text', sa.String(length=500), nullable=True),
    sa.Column('citation_position', sa.Integer(), nullable=True),
    sa.Column('citation_type', sa.String(length=20), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_response_id'], ['ai_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_ai_response_id'), 'citations', ['ai_response_id'], unique=False)
    op.create_index('ix_citations_created_at', 'citations', ['created_at'], unique=False)
    op.create_index('ix_citations_domain', 'citations', ['domain'], unique=False)
    op.create_table('claims',
    sa.Column('ai_response_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('predicate', sa.String(length=100), nullable=False),
    sa.Column('object', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_response_id'], ['ai_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_ai_response_id'), 'claims', ['ai_response_id'], unique=False)
    op.create_index('ix_claims_created_at', 'claims', ['created_at'], unique=False)
    op.create_index('ix_claims_project_created', 'claims', ['project_id', 'created_at'], unique=False)
    op.create_table('competitor_mentions',
    sa.Column('ai_response_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_id', sa.Uuid(), nullable=True),
    sa.Column('competitor_name', sa.String(length=200), nullable=False),
    sa.Column('mention_text', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('recommendation_strength', sa.String(length=10), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_response_id'], ['ai_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_mentions_ai_response_id'), 'competitor_mentions', ['ai_response_id'], unique=False)
    op.create_index('ix_competitor_mentions_competitor_created', 'competitor_mentions', ['competitor_id', 'created_at'], unique=False)
    op.create_index('ix_competitor_mentions_created_at', 'competitor_mentions', ['created_at'], unique=False)
    op.add_column('ai_responses', sa.Column('parser_version', sa.String(length=40), nullable=True))
    op.add_column('ai_responses', sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_responses', sa.Column('parse_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_responses', 'parse_summary')
    op.drop_column('ai_responses', 'parsed_at')
    op.drop_column('ai_responses', 'parser_version')
    op.drop_index('ix_competitor_mentions_created_at', table_name='competitor_mentions')
    op.drop_index('ix_competitor_mentions_competitor_created', table_name='competitor_mentions')
    op.drop_index(op.f('ix_competitor_mentions_ai_response_id'), table_name='competitor_mentions')
    op.drop_table('competitor_mentions')
    op.drop_index('ix_claims_project_created', table_name='claims')
    op.drop_index('ix_claims_created_at', table_name='claims')
    op.drop_index(op.f('ix_claims_ai_response_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_citations_domain', table_name='citations')
    op.drop_index('ix_citations_created_at', table_name='citations')
    op.drop_index(op.f('ix_citations_ai_response_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index('ix_brand_mentions_project_created', table_name='brand_mentions')
    op.drop_index('ix_brand_mentions_created_at', table_name='brand_mentions')
    op.drop_index(op.f('ix_brand_mentions_ai_response_id'), table_name='brand_mentions')
    op.drop_table('brand_mentions')
    # ### end Alembic commands ###
