"""ai providers models and generations

Revision ID: f0e4f4a9ac3f
Revises: 6f34b05b9073
Create Date: 2026-08-22 17:56:40.000721

"""
from collections.abc import Sequence

import json

import sqlalchemy as sa
from alembic import op

from app.ai.catalog import DEFAULT_MODELS, DEFAULT_PROVIDERS
from sqlalchemy.dialects import postgresql

revision: str = 'f0e4f4a9ac3f'
down_revision: str | None = '6f34b05b9073'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_key', sa.String(length=40), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_key')
    )
    op.create_table('ai_models',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('model_key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_key', name='uq_ai_models_provider_model')
    )
    op.create_index('ix_ai_models_created_at', 'ai_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_models_provider_id'), 'ai_models', ['provider_id'], unique=False)
    op.create_table('ai_generations',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('provider_key', sa.String(length=40), nullable=False),
    sa.Column('model_key', sa.String(length=120), nullable=False),
    sa.Column('purpose', sa.String(length=60), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('finish_reason', sa.String(length=30), nullable=True),
    sa.Column('error_category', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('provider_request_id', sa.String(length=200), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('system_prompt_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_generations_created_at', 'ai_generations', ['created_at'], unique=False)
    op.create_index('ix_ai_generations_project_created', 'ai_generations', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_ai_generations_request_id', 'ai_generations', ['request_id'], unique=True)

    # Seed the catalogue from the single source of truth in app.ai.catalog.
    bind = op.get_bind()
    for key, name in DEFAULT_PROVIDERS:
        bind.execute(
            sa.text(
                "INSERT INTO ai_providers (id, name, provider_key, is_enabled, created_at, updated_at) "
                "VALUES (gen_random_uuid(), :name, :key, true, now(), now())"
            ),
            {"name": name, "key": key},
        )
    for provider_key, model_key, display, caps in DEFAULT_MODELS:
        bind.execute(
            sa.text(
                "INSERT INTO ai_models (id, provider_id, model_key, display_name, capabilities, "
                "is_enabled, created_at, updated_at) "
                "SELECT gen_random_uuid(), id, :model_key, :display, CAST(:caps AS jsonb), true, "
                "now(), now() FROM ai_providers WHERE provider_key = :provider_key"
            ),
            {"model_key": model_key, "display": display, "caps": json.dumps(caps), "provider_key": provider_key},
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_generations_request_id', table_name='ai_generations')
    op.drop_index('ix_ai_generations_project_created', table_name='ai_generations')
    op.drop_index('ix_ai_generations_created_at', table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_index(op.f('ix_ai_models_provider_id'), table_name='ai_models')
    op.drop_index('ix_ai_models_created_at', table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
