"""competitive alerts

Revision ID: 2b100994037e
Revises: b56154c699f4
Create Date: 2026-08-23 07:17:08.591811

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "2b100994037e"
down_revision: str | None = "b56154c699f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitive_alerts",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("alert_type", sa.String(length=40), nullable=False),
        sa.Column("competitor_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dedup_key", sa.String(length=400), nullable=False),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name="fk_competitive_alerts_competitor_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_competitive_alerts_project_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "dedup_key", name="uq_competitive_alerts_project_dedup"),
    )
    op.create_index(
        "ix_competitive_alerts_detected_at", "competitive_alerts", ["detected_at"], unique=False
    )
    op.create_index(
        "ix_competitive_alerts_project_id", "competitive_alerts", ["project_id"], unique=False
    )
    op.create_index(
        "ix_competitive_alerts_severity", "competitive_alerts", ["severity"], unique=False
    )
    op.create_index("ix_competitive_alerts_status", "competitive_alerts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_competitive_alerts_status", table_name="competitive_alerts")
    op.drop_index("ix_competitive_alerts_severity", table_name="competitive_alerts")
    op.drop_index("ix_competitive_alerts_project_id", table_name="competitive_alerts")
    op.drop_index("ix_competitive_alerts_detected_at", table_name="competitive_alerts")
    op.drop_table("competitive_alerts")
    # ### end Alembic commands ###
