"""competitive insights

Revision ID: 0ccf1bd24499
Revises: e09c3c62daaf
Create Date: 2026-08-23 05:57:44.495055

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0ccf1bd24499"
down_revision: str | None = "e09c3c62daaf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitive_insights",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("competitor_id", sa.Uuid(), nullable=False),
        sa.Column("insight_type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.String(length=10), nullable=False),
        sa.Column("impact", sa.String(length=10), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("analysis_version", sa.String(length=50), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name="fk_competitive_insights_competitor_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_competitive_insights_project_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id",
            "competitor_id",
            "insight_type",
            name="uq_competitive_insights_project_competitor_type",
        ),
    )
    op.create_index(
        "ix_competitive_insights_competitor_id",
        "competitive_insights",
        ["competitor_id"],
        unique=False,
    )
    op.create_index(
        "ix_competitive_insights_impact", "competitive_insights", ["impact"], unique=False
    )
    op.create_index(
        "ix_competitive_insights_project_id", "competitive_insights", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_competitive_insights_project_id", table_name="competitive_insights")
    op.drop_index("ix_competitive_insights_impact", table_name="competitive_insights")
    op.drop_index("ix_competitive_insights_competitor_id", table_name="competitive_insights")
    op.drop_table("competitive_insights")
    # ### end Alembic commands ###
