"""entity intelligence tables

Revision ID: 3dd3630d9851
Revises: 78e006c1fc69
Create Date: 2026-08-22 06:06:06.563435

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "3dd3630d9851"
down_revision: str | None = "78e006c1fc69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_observations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(length=120), nullable=True),
        sa.Column("entity_name", sa.String(length=500), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_entity_observations_created_at", "entity_observations", ["created_at"], unique=False
    )
    op.create_index(
        "ix_entity_observations_project_code",
        "entity_observations",
        ["project_id", "code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_observations_project_id"),
        "entity_observations",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "entities",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=True),
        sa.Column("structured_data_id", sa.Uuid(), nullable=True),
        sa.Column("scope", sa.Enum("page", "project", name="entity_scope"), nullable=False),
        sa.Column(
            "source_format",
            postgresql.ENUM(
                "json_ld", "microdata", "rdfa", name="structured_data_format", create_type=False
            ),
            nullable=True,
        ),
        sa.Column("entity_type", sa.String(length=120), nullable=False),
        sa.Column("extra_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("same_as", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("identifier", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("json_path", sa.String(length=500), nullable=False),
        sa.Column("fingerprint", sa.String(length=700), nullable=True),
        sa.Column("is_known_type", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["structured_data_id"], ["page_structured_data.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_entities_created_at", "entities", ["created_at"], unique=False)
    op.create_index(op.f("ix_entities_page_id"), "entities", ["page_id"], unique=False)
    op.create_index(
        "ix_entities_project_fingerprint", "entities", ["project_id", "fingerprint"], unique=False
    )
    op.create_index(op.f("ix_entities_project_id"), "entities", ["project_id"], unique=False)
    op.create_index(
        "ix_entities_project_type", "entities", ["project_id", "entity_type"], unique=False
    )
    op.create_table(
        "schema_issues",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("structured_data_id", sa.Uuid(), nullable=True),
        sa.Column(
            "format",
            postgresql.ENUM(
                "json_ld", "microdata", "rdfa", name="structured_data_format", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("json_path", sa.String(length=500), nullable=False),
        sa.Column("block_position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["structured_data_id"], ["page_structured_data.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_schema_issues_created_at", "schema_issues", ["created_at"], unique=False)
    op.create_index(op.f("ix_schema_issues_page_id"), "schema_issues", ["page_id"], unique=False)
    op.create_index(
        "ix_schema_issues_project_code", "schema_issues", ["project_id", "code"], unique=False
    )
    op.create_index(
        op.f("ix_schema_issues_project_id"), "schema_issues", ["project_id"], unique=False
    )
    op.create_table(
        "entity_links",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=False),
        sa.Column("is_authoritative", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_entity_links_created_at", "entity_links", ["created_at"], unique=False)
    op.create_index(op.f("ix_entity_links_entity_id"), "entity_links", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_entity_links_project_id"), "entity_links", ["project_id"], unique=False
    )
    op.create_index(
        "ix_entity_links_project_platform", "entity_links", ["project_id", "platform"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_entity_links_project_platform", table_name="entity_links")
    op.drop_index(op.f("ix_entity_links_project_id"), table_name="entity_links")
    op.drop_index(op.f("ix_entity_links_entity_id"), table_name="entity_links")
    op.drop_index("ix_entity_links_created_at", table_name="entity_links")
    op.drop_table("entity_links")
    op.drop_index(op.f("ix_schema_issues_project_id"), table_name="schema_issues")
    op.drop_index("ix_schema_issues_project_code", table_name="schema_issues")
    op.drop_index(op.f("ix_schema_issues_page_id"), table_name="schema_issues")
    op.drop_index("ix_schema_issues_created_at", table_name="schema_issues")
    op.drop_table("schema_issues")
    op.drop_index("ix_entities_project_type", table_name="entities")
    op.drop_index(op.f("ix_entities_project_id"), table_name="entities")
    op.drop_index("ix_entities_project_fingerprint", table_name="entities")
    op.drop_index(op.f("ix_entities_page_id"), table_name="entities")
    op.drop_index("ix_entities_created_at", table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_entity_observations_project_id"), table_name="entity_observations")
    op.drop_index("ix_entity_observations_project_code", table_name="entity_observations")
    op.drop_index("ix_entity_observations_created_at", table_name="entity_observations")
    op.drop_table("entity_observations")
    sa.Enum(name="entity_scope").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
