"""seo inputs: redirects, validity, structured data

Revision ID: 1e588d19332a
Revises: 4eafda8bad0c
Create Date: 2026-08-22 05:31:18.035034

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "1e588d19332a"
down_revision: str | None = "4eafda8bad0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_structured_data",
        sa.Column(
            "format",
            sa.Enum("json_ld", "microdata", "rdfa", name="structured_data_format"),
            nullable=False,
        ),
        sa.Column("schema_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("page_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["page_id"], ["website_pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_version_id"], ["page_versions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_page_structured_data_page_id"), "page_structured_data", ["page_id"], unique=False
    )
    op.create_index(
        "ix_page_structured_data_page_position",
        "page_structured_data",
        ["page_id", "position"],
        unique=False,
    )
    op.create_index(
        op.f("ix_page_structured_data_project_id"),
        "page_structured_data",
        ["project_id"],
        unique=False,
    )
    op.add_column("crawl_urls", sa.Column("final_url", sa.String(length=2048), nullable=True))
    op.add_column("crawl_urls", sa.Column("redirect_chain", sa.JSON(), nullable=True))
    op.add_column("page_metadata", sa.Column("has_doctype", sa.Boolean(), nullable=False))
    op.add_column("page_metadata", sa.Column("title_count", sa.Integer(), nullable=False))
    op.add_column("page_metadata", sa.Column("canonical_count", sa.Integer(), nullable=False))
    op.add_column(
        "page_metadata", sa.Column("canonical_url", sa.String(length=2048), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("page_metadata", "canonical_url")
    op.drop_column("page_metadata", "canonical_count")
    op.drop_column("page_metadata", "title_count")
    op.drop_column("page_metadata", "has_doctype")
    op.drop_column("crawl_urls", "redirect_chain")
    op.drop_column("crawl_urls", "final_url")
    op.drop_index(op.f("ix_page_structured_data_project_id"), table_name="page_structured_data")
    op.drop_index("ix_page_structured_data_page_position", table_name="page_structured_data")
    op.drop_index(op.f("ix_page_structured_data_page_id"), table_name="page_structured_data")
    op.drop_table("page_structured_data")
    # ### end Alembic commands ###
    sa.Enum(name="structured_data_format").drop(op.get_bind(), checkfirst=True)
